CREATE USER C##MANUEL_ALIAGA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##MANUEL_ALIAGA;

CREATE USER C##PABLO_ALLENDES IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##PABLO_ALLENDES;

CREATE USER C##JAVIER_ANDRADE IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##JAVIER_ANDRADE;

CREATE USER C##CARLA_CARO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##CARLA_CARO;

CREATE USER C##VICENTE_CHANDIA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##VICENTE_CHANDIA;

CREATE USER C##SAMUEL_CONTRERAS IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##SAMUEL_CONTRERAS;

CREATE USER C##BENJAMIN_CARDENAS IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##BENJAMIN_CARDENAS;

CREATE USER C##DIEGO_CORDOVA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##DIEGO_CORDOVA;

CREATE USER C##JAMMIEL_DE_LA_RIVERA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##JAMMIEL_DE_LA_RIVERA;

CREATE USER C##ALHONDRA_DINAMARCA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##ALHONDRA_DINAMARCA;

CREATE USER C##AMARA_DUQUE IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##AMARA_DUQUE;

CREATE USER C##LUIS_DURAN IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##LUIS_DURAN;

CREATE USER C##ARHON_ESPINOZA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##ARHON_ESPINOZA;

CREATE USER C##JASON_EMMANUEL_GONZALEZ IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##JASON_EMMANUEL_GONZALEZ;

CREATE USER C##NAIN_JARA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##NAIN_JARA;

CREATE USER C##MANUEL_MONTECINOS IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##MANUEL_MONTECINOS;

CREATE USER C##BASTIAN_MORENO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##BASTIAN_MORENO;

CREATE USER C##TOMAS_PALMA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##TOMAS_PALMA;

CREATE USER C##DANIELA_PINO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##DANIELA_PINO;

CREATE USER C##JHON_QUIRINO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##JHON_QUIRINO;

CREATE USER C##VICENTE_ROMERO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##VICENTE_ROMERO;

CREATE USER C##VALENTINA_RIOS IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##VALENTINA_RIOS;

CREATE USER C##ARIEL_SERRANO IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##ARIEL_SERRANO;

CREATE USER C##BASTIAN_SAEZ IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##BASTIAN_SAEZ;

CREATE USER C##CRISTOPHER_TOLOZA IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##CRISTOPHER_TOLOZA;

CREATE USER C##BRYAN_VALLEJOS IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##BRYAN_VALLEJOS;

CREATE USER C##JOAQUIN_VILLARROEL IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##JOAQUIN_VILLARROEL;

CREATE USER C##SEBASTIAN_MORALES IDENTIFIED BY Inacap#2025;
GRANT ALL PRIVILEGES TO C##SEBASTIAN_MORALES;